name = "Simple Content component"
description = "Simple component"
destination = "ui.apps/src/main/content/jcr_root/apps/{{.project}}/components/content"
version = "1.0.0"

[[fields]]
name = "id"
question = "Component id"
help = "What is the component id to use"
type = "input"
default = "C-01"

[[fields]]
name = "version"
question = "What is the version for this component"
help = "Versioning for components"
type = "input"
default = "v1"
