sudo: false
language: go
go:
  - 1.12.x
env:
  global:
    - GO111MODULE=on
    - TRAVISBUILD=on
install:
  - go get golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/gojp/goreportcard/cmd/goreportcard-cli
  - go get github.com/gojp/goreportcard
  - go get github.com/danieljoos/wincred
  - go get github.com/konsorten/go-windows-terminal-sequences
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

