sudo: false
language: go
go:
  - 1.14.x
env:
  global:
    - GO111MODULE=on
    - TRAVISBUILD=on
install:
  - go get golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/danieljoos/wincred
  - go get github.com/konsorten/go-windows-terminal-sequences
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  - go get -u github.com/gobuffalo/packr/v2/packr2

