// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "5e84dad6f89ff1231105a38feacf54cf"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"670b499ef11f157d999269f21cf93c0a": "1f8b08000000000000ff7c90c16ac3300c40effe0ae1fbe2e40376ea270cb64329c338caa292c89e251746e9bf8f24f596c2d8d57e3c3d89fd8cf00cf685e634211c222bb24288738a8cacd6f4282153528abc031f0125f61528d4f894c4490e6ef6c42e6c4e770ef93dc7a86efdbe5e9b94e31983de6eeec72695b6e68259eecaae699bd61a733c0e84532fa793a9ddd45bf35996820d3d54132c3f234e69797d1bbd0209e8b82b07ea412314416bf42b6d3a4e655d69f065d255f8d4767f8fbe073ecedf4faa1b0c31838e24fba3d5b2d78d21fe58b1df43fcd774e9acf90e0000fffff564d5c1b9010000",
		"cf36fe40d645ba7e8b67656f82e1f171": "1f8b08000000000000ff9452c16adb4010bdeb2b863db5106b9d6b2197ba2914da53427b30a68c57636982b4b3dd1d252ec1ff5e56b2906cda42747a68e7cd7b6f663c76047760ee8f4abe02042791c04917c493575354945ce4a02c3ed76da617a081c1be0684cd0509de35aa217db0b6666dfa7de9a4b358c99e2c52b7ca0aab1797c19990de0f3aca1e279d9e4b0c21d9149ded90bd75e295bcda27177f4611b5c3f3eb6b19a23c91d3d3c9cefda66a533c534ce796b7e5ba5c9ba2d86e0f4c6d9576bb624acf95297ef5d9c175cafcd2501bf2df1f0d2a70026d9661b90215e81399427f87b19d0ffd30ba03f6ad0e0d57ebdbbf4b9f0d5eea2f95a6040789a00da7e5722667dfc79abc8c5c360fe27f9e9effe128ef67a171e98b5d73752239fd780bb39f6fb982fd41ba71a1a8f0d693989d276ac9a9296438c20477b0358f74547303e691b5a50cbe74580fe093bcf856b0caf8bedbd3088e81229377049f23d65d0e96d9848962461f7b55f1197de5a4e6a680f9339bf1982ea8d7ff60e48179a080115586b60f0d46f6b5d92de7be377f020000ffffee775f6f75030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templates", "../../_templates/")
		b.SetResolver("content-component/settings.toml", packr.Pointer{ForwardBox: gk, ForwardPath: "670b499ef11f157d999269f21cf93c0a"})
		b.SetResolver("extend-core-components/settings.toml", packr.Pointer{ForwardBox: gk, ForwardPath: "cf36fe40d645ba7e8b67656f82e1f171"})
	}()
	return nil
}()
